apiVersion: v1
entries:
  bc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-02-17T16:42:35.3131614Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: b992a104f8dbeace0ee064db534d728f94f75de81d7d9c30672fde62acb98d7a
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: bc
    urls:
    - bc-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2021-02-17T16:42:35.3240311Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
generated: "2021-02-17T16:42:35.2644105Z"
