apiVersion: v1
entries:
  bc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-21T13:41:13.2147209Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 376db482a7b0fa437a9ba4475bdb4b62f5f02a0ae46046d8117e90fdd515a9d3
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: bc
    urls:
    - bc-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2020-12-21T13:41:13.2293746Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
generated: "2020-12-21T13:41:13.1927643Z"
