apiVersion: v1
entries:
  pc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-24T19:06:42.144970868Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 0b241991c441ce65541b5bc63bebefe1242253a97b5fa8fbdc1894437ed12591
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-24T19:06:42.124789967Z"
