apiVersion: v1
entries:
  betaalservice:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-04-09T05:14:45.082235Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 982c8c4c903b1960dcf8a49805a4a1b903a4b49e77c00794a51c68b6f417b50e
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: betaalservice
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - betaalservice-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2021-04-09T05:14:45.1143246Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
generated: "2021-04-09T05:14:45.0533302Z"
