apiVersion: v1
entries:
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2021-03-18T18:27:50.32873Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
  proto-component:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-03-18T18:27:50.3134415Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 93f79994382258cf965026b7ccc0b5820e20241a50dbf69175dc98865bc73239
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: proto-component
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - proto-component-0.1.0.tgz
    version: 0.1.0
generated: "2021-03-18T18:27:50.2974217Z"
